import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from './Component/Navbar/nav'
import Footer from './Footer/page'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NutriCare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
       <Nav/>
       {children}
       <Footer/>
      </body>
    </html>
  );
}
